controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Joint Trajectory Controller (Main controller for coordinated motion)
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Individual Position Controllers (for individual joint control)
    base_rotation_position_controller:
      type: position_controllers/JointPositionController

    shoulder_pitch_position_controller:
      type: position_controllers/JointPositionController

    elbow_pitch_position_controller:
      type: position_controllers/JointPositionController

    wrist_pitch_position_controller:
      type: position_controllers/JointPositionController

    wrist_roll_position_controller:
      type: position_controllers/JointPositionController

    # Group Position Controller (all joints together)
    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    # Group Velocity Controller
    arm_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Force Torque Sensor Broadcaster (for contact sensing)
    tcp_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    forearm_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    wrist_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # IMU Sensor Broadcaster
    arm_imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

# Joint Trajectory Controller Configuration
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

    # PID gains for trajectory tracking
    gains:
      base_rotation_joint:
        p: 150.0
        d: 8.0
        i: 5.0
        i_clamp: 20.0
        ff_velocity_scale: 0.1
      shoulder_pitch_joint:
        p: 180.0
        d: 10.0
        i: 8.0
        i_clamp: 25.0
        ff_velocity_scale: 0.12
      elbow_pitch_joint:
        p: 120.0
        d: 7.0
        i: 6.0
        i_clamp: 18.0
        ff_velocity_scale: 0.1
      wrist_pitch_joint:
        p: 100.0
        d: 6.0
        i: 5.0
        i_clamp: 15.0
        ff_velocity_scale: 0.08
      wrist_roll_joint:
        p: 80.0
        d: 5.0
        i: 4.0
        i_clamp: 12.0
        ff_velocity_scale: 0.06

    constraints:
      stopped_velocity_tolerance: 0.02
      goal_time: 1.0
      base_rotation_joint:
        trajectory: 0.15
        goal: 0.05
      shoulder_pitch_joint:
        trajectory: 0.15
        goal: 0.05
      elbow_pitch_joint:
        trajectory: 0.15
        goal: 0.05
      wrist_pitch_joint:
        trajectory: 0.15
        goal: 0.05
      wrist_roll_joint:
        trajectory: 0.15
        goal: 0.05

# Individual Position Controllers
base_rotation_position_controller:
  ros__parameters:
    joint: base_rotation_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

shoulder_pitch_position_controller:
  ros__parameters:
    joint: shoulder_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

elbow_pitch_position_controller:
  ros__parameters:
    joint: elbow_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

wrist_pitch_position_controller:
  ros__parameters:
    joint: wrist_pitch_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

wrist_roll_position_controller:
  ros__parameters:
    joint: wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Group Position Controller
arm_position_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Group Velocity Controller
arm_velocity_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

# Force Torque Sensor Broadcasters
tcp_force_torque_broadcaster:
  ros__parameters:
    sensor_name: tcp_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tcp_link
    topic_name: tcp_wrench

forearm_force_torque_broadcaster:
  ros__parameters:
    sensor_name: forearm_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: forearm_contact_link
    topic_name: forearm_wrench

wrist_force_torque_broadcaster:
  ros__parameters:
    sensor_name: wrist_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: wrist_contact_link
    topic_name: wrist_wrench

# IMU Sensor Broadcaster
arm_imu_broadcaster:
  ros__parameters:
    sensor_name: arm_imu
    state_interface_names:
      - orientation.x
      - orientation.y
      - orientation.z
      - orientation.w
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z
    frame_id: upper_arm_link
    topic_name: arm_imu/data