controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint State Broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Joint Trajectory Controller (Main controller for coordinated motion)
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Individual Joint Controllers (for isolated PID tuning - using JointTrajectoryController with single joint)
    base_rotation_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    shoulder_pitch_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    elbow_pitch_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    wrist_pitch_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    wrist_roll_joint_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Group Position Controller (all joints together)
    arm_position_controller:
      type: position_controllers/JointGroupPositionController

    # Group Velocity Controller
    arm_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Force Torque Sensor Broadcaster (for contact sensing)
    tcp_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    forearm_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    wrist_force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # IMU Sensor Broadcaster
    arm_imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

# Joint Trajectory Controller Configuration
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

    # ros2_control PID gains - Controls torque output directly
    gains:
      base_rotation_joint:
        p: 1200.0
        d: 50.0
        i: 20.0
        i_clamp: 100.0
        ff_velocity_scale: 1.0
      shoulder_pitch_joint:
        p: 1500.0
        d: 60.0
        i: 25.0
        i_clamp: 120.0
        ff_velocity_scale: 1.2
      elbow_pitch_joint:
        p: 1000.0
        d: 40.0
        i: 15.0
        i_clamp: 80.0
        ff_velocity_scale: 1.0
      wrist_pitch_joint:
        p: 800.0
        d: 35.0
        i: 12.0
        i_clamp: 70.0
        ff_velocity_scale: 0.8
      wrist_roll_joint:
        p: 600.0
        d: 30.0
        i: 10.0
        i_clamp: 60.0
        ff_velocity_scale: 0.6

    constraints:
      stopped_velocity_tolerance: 1.0
      goal_time: 3.0  # Much faster with high PID gains!
      base_rotation_joint:
        trajectory: 0.5
        goal: 0.2
      shoulder_pitch_joint:
        trajectory: 0.5
        goal: 0.2
      elbow_pitch_joint:
        trajectory: 0.5
        goal: 0.2
      wrist_pitch_joint:
        trajectory: 0.5
        goal: 0.2
      wrist_roll_joint:
        trajectory: 0.5
        goal: 0.2

# Individual Joint Controllers (JointTrajectoryController with single joint for isolated PID tuning)
base_rotation_joint_position_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    gains:
      base_rotation_joint:
        p: 150.0
        d: 8.0
        i: 5.0
        i_clamp: 20.0
        ff_velocity_scale: 0.1

shoulder_pitch_joint_position_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    gains:
      shoulder_pitch_joint:
        p: 180.0
        d: 10.0
        i: 8.0
        i_clamp: 25.0
        ff_velocity_scale: 0.12

elbow_pitch_joint_position_controller:
  ros__parameters:
    joints:
      - elbow_pitch_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    gains:
      elbow_pitch_joint:
        p: 120.0
        d: 7.0
        i: 6.0
        i_clamp: 18.0
        ff_velocity_scale: 0.1

wrist_pitch_joint_position_controller:
  ros__parameters:
    joints:
      - wrist_pitch_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    gains:
      wrist_pitch_joint:
        p: 100.0
        d: 6.0
        i: 5.0
        i_clamp: 15.0
        ff_velocity_scale: 0.08

wrist_roll_joint_position_controller:
  ros__parameters:
    joints:
      - wrist_roll_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    gains:
      wrist_roll_joint:
        p: 80.0
        d: 5.0
        i: 4.0
        i_clamp: 12.0
        ff_velocity_scale: 0.06

# Group Position Controller
arm_position_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# Group Velocity Controller
arm_velocity_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

# Force Torque Sensor Broadcasters
tcp_force_torque_broadcaster:
  ros__parameters:
    sensor_name: tcp_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tcp_link
    topic_name: tcp_wrench

forearm_force_torque_broadcaster:
  ros__parameters:
    sensor_name: forearm_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: forearm_contact_link
    topic_name: forearm_wrench

wrist_force_torque_broadcaster:
  ros__parameters:
    sensor_name: wrist_force_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: wrist_contact_link
    topic_name: wrist_wrench

# IMU Sensor Broadcaster
arm_imu_broadcaster:
  ros__parameters:
    sensor_name: arm_imu
    state_interface_names:
      - orientation.x
      - orientation.y
      - orientation.z
      - orientation.w
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z
    frame_id: upper_arm_link
    topic_name: arm_imu/data