humanoid_5dof_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01  # Increased from 0.005 for speed (less precision)
  kinematics_solver_timeout: 10
  kinematics_solver_attempts: 20  # Reduced from 10 for faster failure
  position_only_ik: true  # Only solve for position, ignore orientation (5-DOF arm)