humanoid_5dof_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.5
  kinematics_solver_attempts: 10
  position_only_ik: true  # Only solve for position, ignore orientation (5-DOF arm)