# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    humanoid_5dof_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

humanoid_5dof_arm_controller:
  ros__parameters:
    joints:
      - base_rotation_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
      # - effort
    allow_nonzero_velocity_at_trajectory_end: true