humanoid_arm_5dof:
  ros__parameters:
    # Hardware interface parameters
    use_fake_hardware: true
    fake_sensor_commands: false
    slowdown: 1.0

    # Joint limits (safety limits tighter than URDF limits)
    # NOTE: Velocity and acceleration values reference actuator_specs.yaml
    # See humanoid_arm_control/config/actuator_specs.yaml for motor specifications
    joint_limits:
      base_rotation_joint:
        has_position_limits: true
        min_position: -3.0
        max_position: 3.0
        has_velocity_limits: true
        max_velocity: 20.94  # ROBSTRIDE 04: 20.94 rad/s (200 rpm) - from actuator_specs.yaml
        has_acceleration_limits: true
        max_acceleration: 10.0  # Conservative estimate (will tune with real hardware)
        has_jerk_limits: true
        max_jerk: 100.0

      shoulder_pitch_joint:
        has_position_limits: true
        min_position: -0.5
        max_position: 3.0
        has_velocity_limits: true
        max_velocity: 20.94  # ROBSTRIDE 04: 20.94 rad/s (200 rpm) - from actuator_specs.yaml
        has_acceleration_limits: true
        max_acceleration: 10.0  # Conservative estimate (will tune with real hardware)
        has_jerk_limits: true
        max_jerk: 100.0

      elbow_pitch_joint:
        has_position_limits: true
        min_position: -3.0
        max_position: 3.0
        has_velocity_limits: true
        max_velocity: 20.42  # ROBSTRIDE 03: 20.42 rad/s (195 rpm) - from actuator_specs.yaml
        has_acceleration_limits: true
        max_acceleration: 8.0  # Conservative estimate (will tune with real hardware)
        has_jerk_limits: true
        max_jerk: 80.0

      wrist_pitch_joint:
        has_position_limits: true
        min_position: -0.25
        max_position: 2.7
        has_velocity_limits: true
        max_velocity: 20.42  # ROBSTRIDE 03: 20.42 rad/s (195 rpm) - from actuator_specs.yaml
        has_acceleration_limits: true
        max_acceleration: 8.0  # Conservative estimate (will tune with real hardware)
        has_jerk_limits: true
        max_jerk: 80.0

      wrist_roll_joint:
        has_position_limits: true
        min_position: -3.0
        max_position: 3.0
        has_velocity_limits: true
        max_velocity: 42.94  # ROBSTRIDE 02: 42.94 rad/s (410 rpm) - from actuator_specs.yaml
        has_acceleration_limits: true
        max_acceleration: 15.0  # Conservative estimate (will tune with real hardware)
        has_jerk_limits: true
        max_jerk: 150.0

    # Robstride motor specifications (for future hardware integration)
    # REFERENCE: humanoid_arm_control/config/actuator_specs.yaml for complete specifications
    robstride_motors:
      base_rotation_joint:
        motor_id: 1
        motor_type: "ROBSTRIDE 04"  # Updated from RMD-X8-PRO to match actuator_specs.yaml
        gear_ratio: 9.0
        max_torque: 120.0  # Nm - from actuator_specs.yaml
        max_speed: 20.94   # rad/s (200 rpm) - from actuator_specs.yaml
        encoder_resolution: 16384
        can_id: 0x01

      shoulder_pitch_joint:
        motor_id: 2
        motor_type: "ROBSTRIDE 04"  # Updated from RMD-X8-PRO to match actuator_specs.yaml
        gear_ratio: 9.0
        max_torque: 120.0  # Nm - from actuator_specs.yaml
        max_speed: 20.94   # rad/s (200 rpm) - from actuator_specs.yaml
        encoder_resolution: 16384
        can_id: 0x02

      elbow_pitch_joint:
        motor_id: 3
        motor_type: "ROBSTRIDE 03"  # Updated from RMD-X6 to match actuator_specs.yaml
        gear_ratio: 9.0
        max_torque: 60.0  # Nm - from actuator_specs.yaml
        max_speed: 20.42  # rad/s (195 rpm) - from actuator_specs.yaml
        encoder_resolution: 16384
        can_id: 0x03

      wrist_pitch_joint:
        motor_id: 4
        motor_type: "ROBSTRIDE 03"  # Updated from RMD-X6 to match actuator_specs.yaml
        gear_ratio: 9.0
        max_torque: 60.0  # Nm - from actuator_specs.yaml
        max_speed: 20.42  # rad/s (195 rpm) - from actuator_specs.yaml
        encoder_resolution: 16384
        can_id: 0x04

      wrist_roll_joint:
        motor_id: 5
        motor_type: "ROBSTRIDE 02"  # Updated from RMD-X4 to match actuator_specs.yaml
        gear_ratio: 7.75
        max_torque: 17.0  # Nm - from actuator_specs.yaml
        max_speed: 42.94  # rad/s (410 rpm) - from actuator_specs.yaml
        encoder_resolution: 16384
        can_id: 0x05

    # CAN interface configuration (for real hardware)
    can_interface:
      interface_name: "can0"
      bitrate: 1000000
      timeout_ms: 10
      retry_attempts: 3

    # Contact sensing parameters
    contact_sensing:
      force_threshold: 5.0  # N
      torque_threshold: 1.0 # Nm
      contact_debounce_time: 0.1  # seconds
      publish_rate: 100.0  # Hz